#define COMPARE_ROW_DECL(NAME, LEFT, RIGHT) \
\
extern void NAME ## _row_ ## LEFT ## _ ## RIGHT(char *Target, ml_array_dimension_t *LeftDimension, char *LeftData, ml_array_dimension_t *RightDimension, char *RightData);

#define COMPARE_ROW_LEFT_DECL_BASE(NAME, LEFT) \
COMPARE_ROW_DECL(NAME, LEFT, int8_t) \
COMPARE_ROW_DECL(NAME, LEFT, uint8_t) \
COMPARE_ROW_DECL(NAME, LEFT, int16_t) \
COMPARE_ROW_DECL(NAME, LEFT, uint16_t) \
COMPARE_ROW_DECL(NAME, LEFT, int32_t) \
COMPARE_ROW_DECL(NAME, LEFT, uint32_t) \
COMPARE_ROW_DECL(NAME, LEFT, int64_t) \
COMPARE_ROW_DECL(NAME, LEFT, uint64_t) \
COMPARE_ROW_DECL(NAME, LEFT, float) \
COMPARE_ROW_DECL(NAME, LEFT, double)

#ifdef ML_COMPLEX

#define COMPARE_ROW_LEFT_DECL(NAME, LEFT) \
COMPARE_ROW_LEFT_DECL_BASE(NAME, LEFT) \
COMPARE_ROW_DECL(NAME, LEFT, complex_float) \
COMPARE_ROW_DECL(NAME, LEFT, complex_double)

#else

#define COMPARE_ROW_LEFT_DECL(NAME, LEFT) \
COMPARE_ROW_LEFT_DECL_BASE(NAME, LEFT)

#endif

#define COMPARE_ROW_LEFT_VALUE_DECL_BASE(NAME) \
COMPARE_ROW_VALUE_DECL(NAME, int8_t) \
COMPARE_ROW_VALUE_DECL(NAME, uint8_t) \
COMPARE_ROW_VALUE_DECL(NAME, int16_t) \
COMPARE_ROW_VALUE_DECL(NAME, uint16_t) \
COMPARE_ROW_VALUE_DECL(NAME, int32_t) \
COMPARE_ROW_VALUE_DECL(NAME, uint32_t) \
COMPARE_ROW_VALUE_DECL(NAME, int64_t) \
COMPARE_ROW_VALUE_DECL(NAME, uint64_t) \
COMPARE_ROW_VALUE_DECL(NAME, float) \
COMPARE_ROW_VALUE_DECL(NAME, double)

#ifdef ML_COMPLEX

#define COMPARE_ROW_LEFT_VALUE_DECL(NAME) \
COMPARE_ROW_LEFT_VALUE_DECL_BASE(NAME) \
COMPARE_ROW_VALUE_DECL(NAME, complex_float) \
COMPARE_ROW_VALUE_DECL(NAME, complex_double)

#else

#define COMPARE_ROW_LEFT_VALUE_DECL(NAME) \
COMPARE_ROW_LEFT_VALUE_DECL_BASE(NAME)

#endif

#define COMPARE_ROW_OPS_DECL_BASE(NAME) \
COMPARE_ROW_LEFT_DECL(NAME, int8_t) \
COMPARE_ROW_LEFT_DECL(NAME, uint8_t) \
COMPARE_ROW_LEFT_DECL(NAME, int16_t) \
COMPARE_ROW_LEFT_DECL(NAME, uint16_t) \
COMPARE_ROW_LEFT_DECL(NAME, int32_t) \
COMPARE_ROW_LEFT_DECL(NAME, uint32_t) \
COMPARE_ROW_LEFT_DECL(NAME, int64_t) \
COMPARE_ROW_LEFT_DECL(NAME, uint64_t) \
COMPARE_ROW_LEFT_DECL(NAME, float) \
COMPARE_ROW_LEFT_DECL(NAME, double)

#ifdef ML_COMPLEX

#define COMPARE_ROW_OPS_DECL(NAME) \
COMPARE_ROW_OPS_DECL_BASE(NAME) \
COMPARE_ROW_LEFT_DECL(NAME, complex_float) \
COMPARE_ROW_LEFT_DECL(NAME, complex_double)

#else

#define COMPARE_ROW_OPS_DECL(NAME) \
COMPARE_ROW_OPS_DECL_BASE(NAME)

#endif

COMPARE_ROW_OPS_DECL(eq)
COMPARE_ROW_OPS_DECL(ne)
COMPARE_ROW_OPS_DECL(lt)
COMPARE_ROW_OPS_DECL(gt)
COMPARE_ROW_OPS_DECL(le)
COMPARE_ROW_OPS_DECL(ge)
