#include "infix_impl.h"

#define INFIX_ROW_LEFT_IMPL_BASE(NAME, OP, CTYPE, METH, FN, LEFT) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, uint8_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, int8_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, uint16_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, int16_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, uint32_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, int32_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, uint64_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, int64_t) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, float) \
INFIX_ROW_IMPL(NAME, OP, CTYPE, METH, LEFT, double) \
INFIX_ROW_IMPL_VALUE(NAME, OP, CTYPE, METH, FN, LEFT)

#define INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, LEFT) \
INFIX_ROW_LEFT_IMPL_BASE(NAME, OP, CTYPE, METH, FN, LEFT)

#define INFIX_ROW_LEFT_VALUE_IMPL_BASE(NAME, OP, CTYPE, METH, FN) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, uint8_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, int8_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, uint16_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, int16_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, uint32_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, int32_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, uint64_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, int64_t) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, float) \
INFIX_ROW_VALUE_IMPL(NAME, OP, CTYPE, METH, FN, double) \
INFIX_ROW_VALUE_IMPL_VALUE(NAME, OP, CTYPE, METH, FN)

#define INFIX_ROW_LEFT_VALUE_IMPL(NAME, OP, CTYPE, METH, FN) \
INFIX_ROW_LEFT_VALUE_IMPL_BASE(NAME, OP, CTYPE, METH, FN)

#define INFIX_ROW_OPS_IMPL_BASE(NAME, OP, CTYPE, METH, FN) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, uint8_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, int8_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, uint16_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, int16_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, uint32_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, int32_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, uint64_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, int64_t) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, float) \
INFIX_ROW_LEFT_IMPL(NAME, OP, CTYPE, METH, FN, double) \
INFIX_ROW_LEFT_VALUE_IMPL(NAME, OP, CTYPE, METH, FN)

#define INFIX_ROW_OPS_IMPL(NAME, OP, CTYPE, METH, FN) \
INFIX_ROW_OPS_IMPL_BASE(NAME, OP, CTYPE, METH, FN)

#define INFIX_ROW_ENTRY(INDEX, NAME, LEFT, RIGHT) \
	[INDEX] = NAME ## _row_ ## LEFT ## _ ## RIGHT

#define INFIX_ROW_LEFT_ENTRIES_BASE(INDEX, NAME, LEFT) \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_U8, NAME, LEFT, uint8_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_I8, NAME, LEFT, int8_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_U16, NAME, LEFT, uint16_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_I16, NAME, LEFT, int16_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_U32, NAME, LEFT, uint32_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_I32, NAME, LEFT, int32_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_U64, NAME, LEFT, uint64_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_I64, NAME, LEFT, int64_t), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_F32, NAME, LEFT, float), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_F64, NAME, LEFT, double), \
INFIX_ROW_ENTRY(MAX_FORMATS * (INDEX) + ML_ARRAY_FORMAT_ANY, NAME, LEFT, any)

#define INFIX_ROW_LEFT_ENTRIES(INDEX, NAME, LEFT) \
INFIX_ROW_LEFT_ENTRIES_BASE(INDEX, NAME, LEFT)

#define INFIX_ROW_OPS_ENTRIES_BASE(NAME) \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_U8, NAME, uint8_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_I8, NAME, int8_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_U16, NAME, uint16_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_I16, NAME, int16_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_U32, NAME, uint32_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_I32, NAME, int32_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_U64, NAME, uint64_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_I64, NAME, int64_t), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_F32, NAME, float), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_F64, NAME, double), \
INFIX_ROW_LEFT_ENTRIES(ML_ARRAY_FORMAT_ANY, NAME, any)

#define INFIX_ROW_OPS_ENTRIES(NAME) \
INFIX_ROW_OPS_ENTRIES_BASE(NAME)

typedef void (*infix_row_fn_t)(void *Target, ml_array_dimension_t *LeftDimension, char *LeftData, ml_array_dimension_t *RightDimension, char *RightData);

#define INFIX_FNS(TITLE, NAME, OP, CTYPE, METH, FN) \
	INFIX_ROW_OPS_IMPL(NAME, OP, CTYPE, METH, FN) \
\
infix_row_fn_t Compare ## TITLE ## RowFns[MAX_FORMATS * MAX_FORMATS] = { \
	INFIX_ROW_OPS_ENTRIES(NAME) \
}
